-- +goose Up
CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'inactive'
    CHECK (status IN ('deleted', 'active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO rooms (status) VALUES ('active');

-- +goose Down
DROP TABLE IF EXISTS rooms;
