-- +goose Up
CREATE TABLE IF NOT EXISTS players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fk_room_id BIGINT REFERENCES rooms(id),
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS players;
