// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package dbgen

import (
	"context"
)

const getConfigByID = `-- name: GetConfigByID :one
SELECT id, key, value, description, created_at, updated_at
FROM configs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConfigByID(ctx context.Context, id int64) (Config, error) {
	row := q.db.QueryRow(ctx, getConfigByID, id)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
