// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential.sql

package dbgen

import (
	"context"
)

const getCredentialByName = `-- name: GetCredentialByName :one
SELECT id, name, value, created_at, updated_at
FROM credentials
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetCredentialByName(ctx context.Context, name string) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByName, name)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
