// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Config struct {
	ID          int64
	Key         string
	Value       json.RawMessage
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Credential struct {
	ID        int64
	Name      string
	Value     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Player struct {
	ID          int64
	FkRoomID    pgtype.Int8
	DisplayName pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	FkUserID    pgtype.Int8
}

type Room struct {
	ID        int64
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID             int64
	Username       string
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
