// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package dbgen

import (
	"context"
)

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, fk_room_id, display_name, created_at, updated_at
FROM players
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.FkRoomID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
