// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package dbgen

import (
	"context"
)

const countRooms = `-- name: CountRooms :one
SELECT COUNT(*) FROM rooms WHERE status != 'deleted'
`

func (q *Queries) CountRooms(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRooms)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (status) VALUES ($1) RETURNING id, status, created_at, updated_at
`

func (q *Queries) CreateRoom(ctx context.Context, status string) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, status)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableRoom = `-- name: GetAvailableRoom :one
SELECT r.id, r.status, r.created_at, r.updated_at
FROM rooms r
LEFT JOIN players p ON p.fk_room_id = r.id
WHERE r.status = 'active'
GROUP BY r.id, r.status, r.created_at, r.updated_at
ORDER BY COUNT(p.id) ASC
LIMIT 1
`

func (q *Queries) GetAvailableRoom(ctx context.Context) (Room, error) {
	row := q.db.QueryRow(ctx, getAvailableRoom)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, status, created_at, updated_at
FROM rooms
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
