# syntax=docker/dockerfile:1

FROM golang:1.25.1-alpine

WORKDIR /app

# System deps
RUN apk add --no-cache git ca-certificates && update-ca-certificates

# Optional: trust corporate CA
COPY certs/zscaler.pem /usr/local/share/ca-certificates/zscaler.pem
RUN update-ca-certificates

# Install air
RUN go install github.com/air-verse/air@latest

# Cache Go deps
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

EXPOSE 8080

CMD ["/go/bin/air", "-c", ".air.toml"]
